name: Docker CI

on:
  push:
    branches: ["main"]

jobs:
  build-test-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Login no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build image
        run: |
          IMAGE=diogeneswallis96/load_test_fast_api
          TAG=${{ github.run_number }}

          docker build -f Dockerfile -t $IMAGE:$TAG .

      - name: Run model sanity check
        run: |
          IMAGE=diogeneswallis96/load_test_fast_api
          TAG=${{ github.run_number }}

          docker run --rm \
            -e APP_NAME=test \
            -e MODEL_PATH=/app/model.pkl \
            -e DATABASE_URL=sqlite:///./test.db \
            -e RECORD_ON_DB=false \
            $IMAGE:$TAG \
            python -m app.tests.sanity_check

      - name: Push image (only if tests pass)
        run: |
          IMAGE=diogeneswallis96/load_test_fast_api
          TAG=${{ github.run_number }}

          docker tag $IMAGE:$TAG $IMAGE:latest
          docker push $IMAGE:$TAG
          docker push $IMAGE:latest